# Generated by Django 2.2.4 on 2019-11-28 17:22

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ttipanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarterly_Church_Planting_Update_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', django_countries.fields.CountryField(max_length=2)),
                ('National_Regional_Director_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Mobile_Numbers', models.CharField(blank=True, max_length=100, null=True)),
                ('DATE_OF_REPORTING', models.DateField()),
                ('Paul_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('District', models.CharField(choices=[('Nicobar', 'Nicobar'), ('North Middle Andaman', 'North Middle Andaman'), ('South Andaman', 'South Andaman'), ('Anantapur', 'Anantapur'), ('Chittoor', 'Chittoor'), ('East Godavari', 'East Godavari')], max_length=200)),
                ('Mobile_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('Current_Book', models.CharField(blank=True, max_length=100, null=True)),
                ('Number_of_Timothys', models.IntegerField()),
                ('First_Generation_Church_Plants_Timothy', models.IntegerField()),
                ('Number_of_Titus', models.IntegerField()),
                ('Second_Generation_Church_Plants_Titus_disciple', models.IntegerField()),
                ('Third_Generation_Church_Plants_Titus_disciple', models.IntegerField()),
                ('No_of_new_believers', models.IntegerField()),
                ('Any_Previous_batch_churches_planted', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=200)),
                ('Orphans_Being_Impacted', models.IntegerField()),
                ('Baptisms', models.IntegerField()),
                ('Widows_Being_Impacted', models.IntegerField()),
            ],
        ),
    ]
