# Generated by Django 2.2.4 on 2019-11-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttipanel', '0002_quarterly_church_planting_update_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarterly_church_planting_update_form',
            name='DATE_OF_REPORTING',
        ),
    ]
