# Generated by Django 2.2.4 on 2019-11-28 17:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ttipanel', '0003_remove_quarterly_church_planting_update_form_date_of_reporting'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterly_church_planting_update_form',
            name='DATE_OF_REPORTING',
            field=models.DateField(default=datetime.datetime(2019, 11, 28, 17, 29, 6, 539910, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
