# Generated by Django 2.2.4 on 2019-11-28 17:56

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('ttipanel', '0004_quarterly_church_planting_update_form_date_of_reporting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarterly_church_planting_update_form',
            name='Email',
            field=models.EmailField(default='', max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='quarterly_church_planting_update_form',
            name='Mobile_Number',
            field=phone_field.models.PhoneField(blank=True, default='', help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='quarterly_church_planting_update_form',
            name='Mobile_Numbers',
            field=phone_field.models.PhoneField(blank=True, default='', help_text='Contact phone number', max_length=31),
        ),
    ]
